// Generated by CoffeeScript 1.9.3
var connection, packets;

connection = {
  version: "0.1",
  url: "ws://" + window.location.host + ("/" + vires.room + "/c"),
  messages: new Array(0),
  socket: null,
  init: function() {
    connection.socket = new WebSocket(this.url);
    connection.socket.onopen = function(event) {
      vires.load("lobby");
    };
    connection.socket.onerror = function(event) {};
    connection.socket.onmessage = function(msg) {
      var err;
      try {
        connection.messages.push(JSON.parse(msg.data));
      } catch (_error) {
        err = _error;
        console.error(err);
      }
    };
    connection.socket.onclose = function(closed) {
      vires.load("noConnection");
    };
  },
  send: function(type, payload) {
    var data, packet;
    packet = {
      Type: type,
      Version: this.version,
      Data: payload
    };
    data = JSON.stringify(packet);
    this.socket.send(data);
  },
  sendMove: function(target, sources) {
    var i, len, move, source;
    for (i = 0, len = sources.length; i < len; i++) {
      source = sources[i];
      move = {
        Source: source.ID,
        Dest: target.ID
      };
      this.send("Movement", move);
    }
  },
  defaultDigest: function(Msg) {
    switch (Msg.Type) {
      case "Movement":
        return;
      case "Replication":
        return;
      case "Conflict":
        return;
      case "Collision":
        return;
      case "EliminatedPlayer":
        return;
      case "Winner":
        return;
      case "Field":
        vires.load("match", Msg.Data);
        break;
      case "Join":
        return;
      case "OwnID":
        vires.Self = Msg.Data;
    }
  }
};

packets = {
  field: {
    "Type": "Field",
    "Version": "0.1",
    "Data": {
      "Cells": [
        {
          "ID": 0,
          "Body": {
            "Location": {
              "X": 200,
              "Y": 200
            },
            "Radius": 3
          },
          "Capacity": 10
        }, {
          "ID": 1,
          "Body": {
            "Location": {
              "X": 180,
              "Y": 210
            },
            "Radius": 5
          },
          "Capacity": 10
        }, {
          "ID": 2,
          "Body": {
            "Location": {
              "X": 200,
              "Y": 260
            },
            "Radius": 3
          },
          "Capacity": 10
        }, {
          "ID": 3,
          "Body": {
            "Location": {
              "X": 240,
              "Y": 190
            },
            "Radius": 5
          },
          "Capacity": 10
        }, {
          "ID": 4,
          "Body": {
            "Location": {
              "X": 230,
              "Y": 230
            },
            "Radius": 4
          },
          "Capacity": 10
        }
      ],
      "StartCells": [
        {
          "Owner": 1,
          "Cell": 3
        }, {
          "Owner": 2,
          "Cell": 2
        }
      ],
      "Size": {
        "X": 800,
        "Y": 600
      }
    }
  }
};
